// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

import * as Reprocessing from "Reprocessing/lib/es6/src/Reprocessing.js";

Reprocessing.hotreload("src/index.re");

export {
  
}
/*  Not a pure module */
