// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

import * as Reprocessing           from "Reprocessing/lib/es6/src/Reprocessing.js";
import * as Reprocessing_Env       from "Reprocessing/lib/es6/src/Reprocessing_Env.js";
import * as Reprocessing_Draw      from "Reprocessing/lib/es6/src/Reprocessing_Draw.js";
import * as Reprocessing_Constants from "Reprocessing/lib/es6/src/Reprocessing_Constants.js";

function setup(env) {
  Reprocessing_Env.size(600, 600, env);
  return 0;
}

function draw(state, env) {
  Reprocessing_Draw.background(Reprocessing_Constants.black, env);
  Reprocessing_Draw.fill(Reprocessing_Constants.red, env);
  Reprocessing_Draw.rect(/* tuple */[
        150 + state | 0,
        150
      ], 300, 300, env);
  return state + 1 | 0;
}

Reprocessing.run(setup, /* Some */[draw], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

export {
  setup ,
  draw  ,
  
}
/*  Not a pure module */
