// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

var Reprocessing = require("Reprocessing/src/Reprocessing.js");

Reprocessing.hotreload("src/index.re");

/*  Not a pure module */
